### PR TITLE
Add tsdoc-characters-after-block-tag in allTsdocMessageIds

### LINKED ISSUE #211: tsdoc-characters-after-block-tag not implemented in eslint plugin
# Bug

eslint-ts-doc-plugin crashed when trying to lint the code below, because of the `,`:
```ts
/** @deprecated, hello
```

This error is returned: 
```
> npm run lint --cache
npm WARN invalid config cache=true
npm WARN invalid config Must be a valid filesystem path

> test@1.0.0 lint /Users/guillaumeclochard/Downloads/a
> eslint src --ext .js,.jsx,.ts,.tsx 

TypeError: context.report() called with a messageId of 'tsdoc-characters-after-block-tag' which is not present in the 'messages' config: {
  "error-loading-config-file": "Error loading TSDoc config file:\n{{details}}",
  "error-applying-config": "Error applying TSDoc configuration: {{details}}",
  "tsdoc-at-sign-in-word": "tsdoc-at-sign-in-word: {{unformattedText}}",

...
```

Full error here: https://github.com/guillaumewuip/eslint-tsdoc-error-example/pull/2
Reproduction repo here: https://github.com/guillaumewuip/eslint-tsdoc-error-example

# Expected behavior

No crash. Either the correct `tsdoc-characters-after-block-tag` message is used for this lint error, or something more generic like "TSDoc unknown error message" ?

### PR DESCRIPTION
**Pull request by guillaumewuip**
This fixes #211 by adding the missing `tsdoc-characters-after-block-tag` in `allTsdocMessageIds`

Fixes https://github.com/microsoft/tsdoc/issues/224

### CODE REVIEW

**Comment by guillaumewuip** [comment]
While this will fix this specific error, this doesn't prevent a new error of the same kind to appear again. 

I can help with trying to compute the `allTsdocMessageIds` variable from the `TSDocMessageId` enum content of by providing a fallback in case of missing entry in `allTsdocMessageIds` if one of these options seems good for you :)

**Comment by octogonz** [comment]
@guillaumewuip Thanks for fixing this!  Sorry I overlooked it until now -- something was broken with my email filters for GitHub. :'(

**Comment by octogonz** [comment]
> I can help with trying to compute the `allTsdocMessageIds` variable from the `TSDocMessageId` enum content of by providing a fallback in case of missing entry in `allTsdocMessageIds` if one of these options seems good for you :)

The problem is that `TSDocMessageId` is a `const enum` instead of a regular `enum`.  We should probably fix that, but it seems like it might be a breaking API change. (?)  Let's tackle it as a separate PR so it doesn't hold up your fix here.

**Comment by octogonz** [comment]
@guillaumewuip Could you sign the CLA?

**Comment by guillaumewuip** [comment]
Hi @octogonz, I've just signed the CLA ✔️

**Comment by octogonz** [comment]
This fix was released with `tsdoc` version `0.12.19` and `eslint-plugin-tsdoc` version `0.2.4`.

**Pull request merged**
